package com.ecommerce.project.repositories;

import com.ecommerce.project.model.Category;
import org.springframework.data.jpa.repository.JpaRepository;

public interface CategoryRepository extends JpaRepository<Category, Long> {

    //Parameters are < , > Entity and Its primary key data type
    // here, Entity = Category and Primary Key type is Long

    //With JpaRepository we get boilerplate implementation such as save(), findAll()
    //FindBy(). Delete()etc we do not have to create an implementation call for repository
    //it will be generated by spring boot


}
